// The atlas glyph map: one Carbon icon per registry slug, consumed not modified. It lived in the
// mother-only components atlas page until v6.36.0; it moved into the kit so the showroom's surface
// register (the HQ Components index, the CD reference-surface boards) can draw the same glyph per
// row, and forks carry it with the rest of the sync unit. A slug without an entry falls back to
// CircleDash in the consumer, so a component that ships before its glyph is picked still renders.
import {
  ButtonCentered,
  RowExpand,
  StringText,
  Calendar,
  CalendarHeatMap,
  Checkbox,
  Choices,
  RadioButton,
  ToggleOn,
  ListDropdown,
  TextWrap,
  SettingsAdjust,
  Search,
  TagGroup,
  ListBoxes,
  Time,
  Group,
  Password,
  StarFilled,
  ColorPalette,
  Template,
  Notification,
  Filter,
  Folders,
  Popup,
  Menu,
  BottomPanelOpen,
  ChartLine,
  ChartBar,
  ChartDonut,
  Heading as HeadingIcon,
  TextLongParagraph,
  TextSmallCaps,
  Image as ImageIcon,
  Video as VideoIcon,
  CarouselHorizontal,
  CircleDash,
  CenterToFit,
  Row as RowIcon,
  Column as ColumnIcon,
  Subtract,
  Meter,
  Tag,
  Badge as BadgeIcon,
  UserAvatar,
  OverflowMenuVertical,
  Pen,
  CircleFilled,
  Camera,
  TableOfContents,
  PageNumber,
  Dashboard,
  MediaLibrary,
  Workspace,
  OpenPanelTop,
  OpenPanelLeft,
  ParentChild,
  MacCommand,
  Information,
  InformationSquare,
  Receipt,
  ChartStacked,
  ChartMarimekko,
  WordCloud,
  Barcode,
  DotMark,
  CurrencyDollar,
  SummaryKpi,
  DataTable,
  Roadmap,
  Fire,
  SkillLevel,
  CategoricalPalette,
  Notebook,
  ListBulleted,
  Keyboard,
  ImageSearch,
  Quotes,
  Gradient,
  Email,
  UpToTop,
  Eyedropper,
  Shapes,
  HorizontalView,
  ViewMode_2,
  ArrowsVertical,
  ShowDataCards,
  ImageCopy,
  Hourglass,
  AiGenerate,
  Chat,
  Send,
  View,
  Box,
  Identification,
  Help,
  NotificationNew,
  AlignBoxTopLeft,
  Analytics,
  Grid,
  ProgressBar as ProgressBarIcon,
  RequestQuote,
  CloudUpload,
  Label,
  Purchase,
  ListChecked,
  Milestone,
  DataTableReference,
  Rss,
  ToolsAlt,
  ContentView,
  type CarbonIconType,
} from "@carbon/icons-react";

// Leading glyph per component (slug -> Carbon icon, consumed not modified). Not every
// registry slug has an entry here: a slug without a chosen icon falls back to CircleDash
// in GROUPS below, so a component that ships before its glyph is picked still renders.
export const ATLAS_ICONS: Record<string, CarbonIconType> = {
  accordion: RowExpand,
  button: ButtonCentered,
  input: StringText,
  textarea: TextWrap,
  "prompted-textarea": Pen,
  "segmented-control": ViewMode_2,
  "date-picker": Calendar,
  "date-range-picker": CalendarHeatMap,
  "time-picker": Time,
  select: ListDropdown,
  combobox: Search,
  search: Search,
  "multi-select": TagGroup,
  listbox: ListBoxes,
  slider: SettingsAdjust,
  checkbox: Checkbox,
  "choice-card": Choices,
  radio: RadioButton,
  switch: ToggleOn,
  "form-group": Group,
  otp: Password,
  rating: StarFilled,
  "scorecard-dots": CircleFilled,
  "color-picker": ColorPalette,
  "photo-strip": Camera,
  card: Template,
  toast: Notification,
  tabs: Folders,
  "tab-links": ShowDataCards,
  modal: Popup,
  "dropdown-menu": OverflowMenuVertical,
  tooltip: Information,
  nav: Menu,
  footer: BottomPanelOpen,
  "filter-panel": Filter,
  "page-nav": TableOfContents,
  pagination: PageNumber,
  panel: Dashboard,
  toolbar: ToolsAlt,
  "record-card": ContentView,
  "asset-card": MediaLibrary,
  "app-shell": Workspace,
  "top-bar": OpenPanelTop,
  "nav-rail": OpenPanelLeft,
  breadcrumbs: ParentChild,
  "command-palette": MacCommand,
  "callout-card": InformationSquare,
  "invoice-paper": Receipt,
  "line-chart": ChartLine,
  "bar-chart": ChartBar,
  "donut-chart": ChartDonut,
  "stacked-bar-chart": ChartStacked,
  "channel-split-bar": ChartMarimekko,
  "word-frequency-cloud": WordCloud,
  "id-chip": Barcode,
  "legend-dot": DotMark,
  "price-label": CurrencyDollar,
  stat: SummaryKpi,
  table: DataTable,
  timeline: Roadmap,
  "streak-strip": Fire,
  "tiered-rung": SkillLevel,
  "swatch-row": CategoricalPalette,
  "diary-entry": Notebook,
  "line-item-row": ListBulleted,
  heading: HeadingIcon,
  prose: TextLongParagraph,
  eyebrow: TextSmallCaps,
  glance: Meter,
  "data-label": Tag,
  badge: BadgeIcon,
  avatar: UserAvatar,
  image: ImageIcon,
  video: VideoIcon,
  marquee: CarouselHorizontal,
  kbd: Keyboard,
  lightbox: ImageSearch,
  "provenance-quote": Quotes,
  "hero-banner": Gradient,
  "contact-strip": Email,
  icon: Shapes,
  section: HorizontalView,
  container: CenterToFit,
  row: RowIcon,
  column: ColumnIcon,
  spacer: ArrowsVertical,
  divider: Subtract,
  "back-to-top": UpToTop,
  "token-row": Eyedropper,
  carousel: ImageCopy,
  skeleton: Hourglass,
  "ai-card": AiGenerate,
  "chat-message": Chat,
  "chat-composer": Send,
  "chat-context-card": View,
  "empty-state": Box,
  "brand-lockup": Identification,
  "help-modal": Help,
  "notifications-button": NotificationNew,
  "page-head": AlignBoxTopLeft,
  "stat-band": Analytics,
  "panel-grid": Grid,
  "progress-bar": ProgressBarIcon,
  "form-modal": RequestQuote,
  "file-upload": CloudUpload,
  "text-field": Label,
  "pricing-card": Purchase,
  "bulk-action-bar": ListChecked,
  stepper: Milestone,
  "data-table": DataTableReference,
  "notification-feed": Rss,
};


export type { CarbonIconType };

// The glyph for a slug, CircleDash where none is picked yet.
export function atlasIconFor(slug: string): CarbonIconType {
  return ATLAS_ICONS[slug] ?? CircleDash;
}
